export const restaurantData = {
  admin: {
    phoneNumbers: ['+37377432554', '+37361058107'],
    emails: ['admin@restaurant.app'],
  },
  payment: {
    currency: 'MDL',
    provider: 'demo',
    environment: 'test',
    demoMode: true,
    deliveryFee: 20,
    minOrderAmount: 0,
    enabledMethods: {
      cash: true,
      card: true,
      online: true,
    },
    providerPublicName: 'Demo Pay',
    webhookPath: '/functions/v1/payment-webhook',
  },
  restaurant: {
    name: 'Restaurant App',
    logo: '',
    tagline: 'Авторская кухня, теплый сервис и атмосфера большого вечера каждый день.',
    description:
      'Премиальный ресторанный шаблон для доставки, бронирования и презентации заведения. Все ключевые данные легко заменить под новый бренд.',
    phone: '+373 22 000 000',
    email: 'hello@restaurant.app',
    address: 'ул. Центральная, 24, Кишинев',
    social: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      telegram: 'https://t.me/sn4ik23',
    },
    colors: {
      primary: '#d8b35f',
      background: '#080706',
      surface: '#14110e',
    },
    heroImage:
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1800&q=85',
    interiorImage:
      'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1600&q=85',
  },
  categories: ['Завтраки', 'Салаты', 'Основные блюда', 'Десерты', 'Напитки'],
  menuItems: [
    {
      id: 'breakfast-1',
      name: 'Бриошь с лососем',
      category: 'Завтраки',
      description: 'Нежная бриошь, слабосоленый лосось, сливочный крем и зелень.',
      price: 165,
      popular: true,
      image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'breakfast-2',
      name: 'Сырники с ванилью',
      category: 'Завтраки',
      description: 'Воздушные сырники, ягодный соус, фермерская сметана.',
      price: 115,
      popular: false,
      image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'salad-1',
      name: 'Салат с бурратой',
      category: 'Салаты',
      description: 'Буррата, томаты, руккола, базилик и оливковое масло.',
      price: 185,
      popular: true,
      image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'salad-2',
      name: 'Цезарь с креветками',
      category: 'Салаты',
      description: 'Креветки гриль, романо, пармезан, хрустящие крутоны.',
      price: 175,
      popular: false,
      image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'main-1',
      name: 'Стейк с перечным соусом',
      category: 'Основные блюда',
      description: 'Говяжий стейк, перечный соус, печеные овощи и микрозелень.',
      price: 345,
      popular: true,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'main-2',
      name: 'Паста с трюфелем',
      category: 'Основные блюда',
      description: 'Свежая паста, сливочный соус, пармезан и трюфельное масло.',
      price: 245,
      popular: true,
      image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'dessert-1',
      name: 'Шоколадный фондан',
      category: 'Десерты',
      description: 'Горячий шоколадный фондан с ванильным мороженым.',
      price: 125,
      popular: false,
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
    },
    {
      id: 'drink-1',
      name: 'Авторский лимонад',
      category: 'Напитки',
      description: 'Цитрус, мята, ягоды и легкая газированная основа.',
      price: 75,
      popular: false,
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80',
    },
  ],
  benefits: [
    'Свежие сезонные продукты',
    'Быстрая доставка и самовывоз',
    'Онлайн-бронь без звонков',
    'Готовый шаблон под любой бренд',
  ],
  testimonials: [
    {
      name: 'Анна',
      text: 'Уютная атмосфера, красивые блюда и очень понятное меню. Заказ оформила за минуту.',
    },
    {
      name: 'Дмитрий',
      text: 'Выглядит как приложение дорогого ресторана. Особенно понравилась мобильная версия.',
    },
    {
      name: 'Мария',
      text: 'Бронирование работает просто и аккуратно, без лишних шагов.',
    },
  ],
  openingHours: [
    { day: 'Пн-Чт', time: '09:00 - 22:00' },
    { day: 'Пт-Сб', time: '09:00 - 00:00' },
    { day: 'Вс', time: '10:00 - 22:00' },
  ],
};
